webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db

class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(52), index=True, unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    full_name = db.Column(db.String, unique=True, nullable=False)
    role = db.Column(db.String(12), index=True, nullable=False)
    id_major = db.Column(db.Integer, nullable=True)
    id_prof = db.Column(db.Integer, nullable=True)
    id_depart = db.Column(db.Integer, nullable=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role =='admin'

    @property
    def is_department(self):
        return self.role =='department'

    @property
    def is_student(self):
        return self.role =='student'

    def __repr__(self):
        return '<Пользователь {} {}>'.format(self.full_name, self.role)
        #return format(self.full_name)


class Depart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    depart_name = db.Column(db.String(120), index=True, unique=True, nullable=False)
    full_name = db.Column(db.String(255), unique=True, nullable=False)
    
    def __repr__(self):
        return '<Кафедра {} {}>'.format(self.depart_name, self.full_name)

webapp/user/forms.py
from flask_wtf import FlaskForm
from webapp.user.models import Users
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, EqualTo, ValidationError
#from wtforms.validators import DataRequired, Email, EqualTo  # было бы с Email, если бы у нас был email в форме регистрации 

class LoginForm(FlaskForm):
    username = StringField("Имя пользователя", validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField("Пароль", validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField("Отправить", render_kw={"class": "btn btn-primary"})

webapp/user/views.py
from flask import Blueprint, Flask, flash, current_app, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm
from webapp.user.models import Users

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = "Авторизация на сайте"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process_login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(user_name=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно зашли на сайт')
            if user.role =='admin':
                return redirect(url_for('admin.admin_index'))
            elif user.role =='department':
                depart_id = user.id_depart
                return redirect(url_for('test.test_index', depart_id=depart_id))
            elif user.role =='student':
                user_id = user.id
                #prof_id = user.id_prof
                return redirect(url_for('test.test_student', user_id=user_id))
            else:
                return redirect(url_for('index'))
    
    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы вышли из системы.')
    return redirect(url_for('index'))

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %} 
    <div class="row">
        <div class="col-4">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }} <br>
                    {% endfor %}
                
                </div>
                {% endif %}
            {% endwith %}
            <form action="{{ url_for('user.process_login') }}" method="POST"> <!-- в   -->
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username() }}
            </div>
            <div class="form-group">
                {{ form.password.label }} <br>
                {{ form.password() }}
            </div>
            <div class="form-group form-check">
                {{ form.remember_me() }}
                {{ form.remember_me.label(class_='form-check-label') }} 
                
            </div>
            <p>
                {{ form.submit() }}
            </p>
        </form>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
           
        </div>
    </div>
{% endblock %}