webapp/user/views.py
from flask import Blueprint, Flask, flash, current_app, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm
from webapp.user.models import Users

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = "Авторизация на сайте"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process_login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(user_name=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно зашли на сайт')
            if user.role =='admin':
                return redirect(url_for('admin.admin_index'))
            elif user.role =='department':
                depart_id = user.id_depart
                return redirect(url_for('test.test_index', depart_id=depart_id))
            elif user.role =='student':
                user_id = user.id
                #prof_id = user.id_prof
                return redirect(url_for('test.test_student', user_id=user_id))
            else:
                return redirect(url_for('index'))
    
    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы вышли из системы.')
    return redirect(url_for('index'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styleMy.css') }}">
    <title>{{ page_title}}</title>
  </head>
  <body>
      {% include "menu.html" %}
    <div class="container">
        <!--  <h1 style="text-align: center;">{{ page_title}}</h1> -->
        <br>
        {% block content %} {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- import plugin script  Chart.js-->
  </body>
</html>

webapp/templates/index.html
{% extends "base.html" %}

{% block content %} 
<div class="row">
    <div class="col-2">

    </div>
    <div class="col-8">
        <br> {{ mess }} <br>   
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }} <br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        {% if current_user.is_authenticated %}
         <h2>Добро пожаловать!</h2>
        <p> Начальная страница</p>
        {% else %}
        <h1 style="text-align: center;">{{ page_title}}</h1>
        <p style="text-align: center;"> <img src="/static/img/pc1.png"></p>
        {% endif %}
 
    </div>        
    <div class="col-2">

    </div>
    </div>
  {% endblock %}

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ page_title}}</title>
  </head>
  <body>
    <div class="container">
        <h1>{{ page_title}}</h1>
    <div class="row">
        <div class="col-4">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }} <br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <form action="{{ url_for('process_login') }}" method="POST"> <!-- в   -->
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username() }}
            </div>
            <div class="form-group">
                {{ form.password.label }} <br>
                {{ form.password() }}
            </div>
            <p>
                {{ form.submit() }}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            
        </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">On-line test</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if current_user.is_admin %}
            <li class="nav-item active">
                <a class="nav-link hlink" href="{{ url_for('admin.admin_index') }}">Админка <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link hlink" href="{{ url_for('admin.register') }}">Добавить пользователя </a>
            </li>
            <li class="nav-item">
              <a class="nav-link hlink" href="{{ url_for('admin.register') }}">Добавить направление</a>
          </li>
          <li class="nav-item">
            <a class="nav-link hlink" href="{{ url_for('admin.register') }}">Добавить профиль</a>
        </li>
            {% endif %}
            {% if current_user.is_department %}
            <li class="nav-item active">
                <a class="nav-link hlink" href="{{ url_for('test.test_index', depart_id=depart_id) }}">Ваши тесты <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link hlink" href="{{ url_for('test.input', depart_id=depart_id) }}">Добавить новый вопрос</a>
            </li>
            <li class="nav-item">
                <a class="nav-link hlink" href="{{ url_for('test.input_kurs', depart_id=depart_id) }}">Добавить новый курс</a>
            </li>
            <li class="nav-item">
             <!--   <a class="nav-link hlink" href="{{ url_for('test.view_res') }}">Просмотр результатов</a> -->
          </li>
            {% endif %}
            {% if current_user.is_student %}
            <li class="nav-item">
                <a class="nav-link hlink" href="{{ url_for('test.test_student', user_id=current_user.id) }}">Выбор теста <span class="sr-only">(current)</span></a>
              </li>
            <li class="nav-item">
             <a class="nav-link hlink" href="{{ url_for('test.view_res') }}">Просмотр результатов</a>   
            </li>
            {% endif %}
          </ul> 
    <!--      <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
          </form> -->
        <ul class="navbar-nav">
           {% if current_user.is_authenticated %}
            <li class="nav-item">   
                {% if current_user.is_department %}
                <span class="nav-link">Здравствуйте, кафедра {{ current_user.full_name }}</span>
                {% else %}
                <span class="nav-link">Здравствуйте, {{ current_user.full_name }}</span>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link hlink" href="{{ url_for('user.logout') }}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link hlink" href="{{ url_for('user.login') }}">Войти</a>
            </li>
            {% endif %}
        </ul>
        </div>
      </nav>